// GENERATED by scripts/bundle-mcp-core.mjs — do not edit by hand.
// Source of truth: src/lib/connectorCore/index.ts. Run `npm run bundle:mcp` to refresh.

// src/lib/connectorCore/writing.ts
function stripHtml(html) {
  const text = (html ?? "").replace(/<(p|div|br|h[1-6])[^>]*>/gi, "\n").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'");
  return text.replace(/\n{3,}/g, "\n\n").trim();
}
function countWords(text) {
  const matches = text.match(/\S+/g);
  return matches ? matches.length : 0;
}
async function listManuscripts(client, userId) {
  const { data, error } = await client.from("manuscripts").select("id, title, status, word_count, book_id, source_filename, updated_at").eq("user_id", userId).order("updated_at", { ascending: false });
  if (error) throw error;
  return data ?? [];
}
async function getManuscript(client, userId, manuscriptId) {
  const { data: manuscript, error: mErr } = await client.from("manuscripts").select("id, title, status, word_count, book_id, source_filename, created_at, updated_at").eq("user_id", userId).eq("id", manuscriptId).maybeSingle();
  if (mErr) throw mErr;
  if (!manuscript) return null;
  const { data: chapterRows, error: cErr } = await client.from("manuscript_chapters").select("id, idx, title, word_count").eq("user_id", userId).eq("manuscript_id", manuscriptId).order("idx", { ascending: true });
  if (cErr) throw cErr;
  const chapters = chapterRows ?? [];
  const totalWordCount = chapters.reduce((sum, c) => sum + (c.word_count ?? 0), 0);
  return {
    id: manuscript.id,
    title: manuscript.title,
    status: manuscript.status,
    // Prefer the summed chapter total; fall back to the stored rollup.
    word_count: chapters.length ? totalWordCount : manuscript.word_count ?? 0,
    book_id: manuscript.book_id ?? null,
    source_filename: manuscript.source_filename ?? null,
    created_at: manuscript.created_at,
    updated_at: manuscript.updated_at,
    chapterCount: chapters.length,
    chapters
  };
}
async function getChapter(client, userId, chapterId) {
  const { data, error } = await client.from("manuscript_chapters").select("id, manuscript_id, idx, title, content_html, word_count, created_at, updated_at").eq("user_id", userId).eq("id", chapterId).maybeSingle();
  if (error) throw error;
  if (!data) return null;
  return data;
}
async function getManuscriptPlainText(client, userId, manuscriptId) {
  const { data: manuscript, error: mErr } = await client.from("manuscripts").select("id, title").eq("user_id", userId).eq("id", manuscriptId).maybeSingle();
  if (mErr) throw mErr;
  if (!manuscript) return null;
  const { data: chapterRows, error: cErr } = await client.from("manuscript_chapters").select("idx, title, content_html").eq("user_id", userId).eq("manuscript_id", manuscriptId).order("idx", { ascending: true });
  if (cErr) throw cErr;
  const text = (chapterRows ?? []).map((c) => {
    const heading = c.title || "Untitled chapter";
    return `=== ${heading} ===

${stripHtml(c.content_html)}`;
  }).join("\n\n");
  return {
    manuscriptId: manuscript.id,
    title: manuscript.title,
    text,
    wordCount: countWords(text)
  };
}
function countWordsHtml(html) {
  const text = (html ?? "").replace(/<[^>]+>/g, " ");
  const matches = text.match(/\S+/g);
  return matches ? matches.length : 0;
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function contentToHtml(content) {
  const raw = content ?? "";
  if (/<[a-z][^>]*>/i.test(raw)) return raw;
  const paragraphs = raw.split(/\n\s*\n/).map((p) => p.trim()).filter((p) => p.length > 0);
  if (paragraphs.length === 0) return "";
  return paragraphs.map((p) => `<p>${escapeHtml(p).replace(/\n/g, "<br>")}</p>`).join("\n");
}
function todayISOLocal() {
  const d = /* @__PURE__ */ new Date();
  return new Date(d.getTime() - d.getTimezoneOffset() * 6e4).toISOString().slice(0, 10);
}
async function createManuscript(client, userId, args) {
  const { data, error } = await client.from("manuscripts").insert({
    user_id: userId,
    title: args.title,
    status: "draft",
    word_count: 0,
    book_id: args.bookId ?? null
  }).select("id, title, status, word_count, book_id, source_filename, updated_at").single();
  if (error) throw error;
  return data;
}
async function appendManuscriptChapter(client, userId, args) {
  const { data: manuscript, error: mErr } = await client.from("manuscripts").select("id").eq("id", args.manuscriptId).eq("user_id", userId).maybeSingle();
  if (mErr) throw mErr;
  if (!manuscript) throw new Error(`Manuscript not found: ${args.manuscriptId}`);
  const { data: idxRows, error: idxErr } = await client.from("manuscript_chapters").select("idx").eq("user_id", userId).eq("manuscript_id", args.manuscriptId).order("idx", { ascending: false }).limit(1);
  if (idxErr) throw idxErr;
  const nextIdx = idxRows && idxRows.length ? idxRows[0].idx + 1 : 0;
  const contentHtml = contentToHtml(args.content);
  const wordCount = countWordsHtml(contentHtml);
  const { data: inserted, error: insErr } = await client.from("manuscript_chapters").insert({
    manuscript_id: args.manuscriptId,
    user_id: userId,
    idx: nextIdx,
    title: args.title,
    content_html: contentHtml,
    word_count: wordCount
  }).select("id, manuscript_id, idx, title, content_html, word_count, created_at, updated_at").single();
  if (insErr) throw insErr;
  const chapter = inserted;
  const { data: allChapters, error: sumErr } = await client.from("manuscript_chapters").select("word_count").eq("user_id", userId).eq("manuscript_id", args.manuscriptId);
  if (sumErr) throw sumErr;
  const total = (allChapters ?? []).reduce((sum, c) => sum + (c.word_count ?? 0), 0);
  const { error: updErr } = await client.from("manuscripts").update({ word_count: total }).eq("id", args.manuscriptId).eq("user_id", userId);
  if (updErr) throw updErr;
  const { error: logErr } = await client.from("manuscript_word_logs").upsert(
    { manuscript_id: args.manuscriptId, user_id: userId, day: todayISOLocal(), word_count: total },
    { onConflict: "manuscript_id,day" }
  );
  if (logErr) throw logErr;
  return chapter;
}

// src/lib/connectorCore/catalog.ts
var BOOK_LIST_COLUMNS = "id, title, subtitle, series, series_position, status, language, parent_book_id, publish_date, pre_order_date, ebook_price, paperback_price, hardcover_price, audiobook_price, created_at, updated_at";
async function listBooks(client, userId) {
  const { data, error } = await client.from("books").select(BOOK_LIST_COLUMNS).eq("user_id", userId).order("series", { ascending: true, nullsFirst: false }).order("series_position", { ascending: true, nullsFirst: false }).order("created_at", { ascending: false });
  if (error) throw error;
  return data ?? [];
}
async function getBook(client, userId, bookId) {
  const { data, error } = await client.from("books").select("*").eq("user_id", userId).eq("id", bookId).maybeSingle();
  if (error) throw error;
  return data ?? null;
}
async function listPenNames(client, userId) {
  const { data, error } = await client.from("pen_names").select("id, name, color, notes, created_at, updated_at").eq("user_id", userId).order("name", { ascending: true });
  if (error) throw error;
  return data ?? [];
}
var OPPORTUNITY_DECISION_VALUES = ["dismissed", "planned"];
async function setOpportunityDecision(client, userId, args) {
  if (!args.bookId) throw new Error("setOpportunityDecision: bookId is required");
  if (!args.opportunityKey) throw new Error("setOpportunityDecision: opportunityKey is required");
  if (!OPPORTUNITY_DECISION_VALUES.includes(args.decision)) {
    throw new Error(
      `setOpportunityDecision: invalid decision '${args.decision}' (expected ${OPPORTUNITY_DECISION_VALUES.map((v) => `'${v}'`).join(" | ")})`
    );
  }
  const { error } = await client.from("book_opportunity_decisions").upsert(
    {
      user_id: userId,
      book_id: args.bookId,
      opportunity_key: args.opportunityKey,
      decision: args.decision
    },
    { onConflict: "user_id,book_id,opportunity_key" }
  );
  if (error) throw error;
}

// src/lib/connectorCore/arcs.ts
var READER_SELECT = "id, name, email, status, primary_sm, newsletter_subscribed, promo_team, updated_at, reader_books:arc_reader_books(book_id, relationship, book:books!book_id(title))";
function flattenBooks(rows) {
  if (!Array.isArray(rows)) return [];
  return rows.map((rb) => {
    const row = rb;
    return {
      book_id: row.book_id,
      book_title: row.book?.title ?? "(deleted)",
      relationship: row.relationship
    };
  });
}
async function listArcReaders(client, userId) {
  const { data, error } = await client.from("arc_readers").select(READER_SELECT).eq("user_id", userId).order("name", { ascending: true });
  if (error) throw error;
  return (data ?? []).map((raw) => {
    const r = raw;
    return {
      id: r.id,
      name: r.name,
      email: r.email ?? null,
      status: r.status,
      primary_sm: r.primary_sm ?? null,
      newsletter_subscribed: Boolean(r.newsletter_subscribed),
      promo_team: Boolean(r.promo_team),
      books: flattenBooks(r.reader_books),
      updated_at: r.updated_at
    };
  });
}
async function getArcStats(client, userId) {
  const { data, error } = await client.from("arc_readers").select("status").eq("user_id", userId);
  if (error) throw error;
  const rows = data ?? [];
  const byStatus = {};
  for (const row of rows) {
    const status = row.status ?? "unknown";
    byStatus[status] = (byStatus[status] ?? 0) + 1;
  }
  return { total: rows.length, byStatus };
}

// src/modules/profit-track/utils/calculations.ts
var calculateMetrics = (record, categories) => {
  const legacyAds = (record.pnrAds || 0) + (record.contempAds || 0) + (record.trafficAds || 0) + (record.miscAds || 0);
  const legacyRev = (record.shopifyRev || 0) + (record.amazonRev || 0) + (record.d2dRev || 0) + (record.googleRev || 0) + (record.koboRev || 0) + (record.koboPlusRev || 0);
  let customAds = 0;
  let customRev = 0;
  if (categories && record.customAmounts) {
    for (const cat of categories) {
      if (cat.legacyColumn) continue;
      const amt = record.customAmounts[cat.id] || 0;
      if (cat.type === "ad") customAds += amt;
      else customRev += amt;
    }
  }
  const totalAdSpend = legacyAds + customAds;
  const totalRevenue = legacyRev + customRev;
  const netRevenue = totalRevenue - totalAdSpend;
  const roas = totalAdSpend > 0 ? totalRevenue / totalAdSpend : 0;
  const adsToIncomePercent = totalRevenue > 0 ? totalAdSpend / totalRevenue : 0;
  return { totalAdSpend, totalRevenue, netRevenue, roas, adsToIncomePercent };
};

// src/modules/profit-track/utils/mappers.ts
function dailyRecordFromDb(row) {
  return {
    id: row.id,
    date: row.date,
    pnrAds: Number(row.pnr_ads) || 0,
    contempAds: Number(row.contemp_ads) || 0,
    trafficAds: Number(row.traffic_ads) || 0,
    miscAds: Number(row.misc_ads) || 0,
    shopifyRev: Number(row.shopify_rev) || 0,
    amazonRev: Number(row.amazon_rev) || 0,
    d2dRev: Number(row.d2d_rev) || 0,
    googleRev: Number(row.google_rev) || 0,
    koboRev: Number(row.kobo_rev) || 0,
    koboPlusRev: Number(row.kobo_plus_rev) || 0,
    customAmounts: normalizeCustomAmounts(row.custom_amounts)
  };
}
function normalizeCustomAmounts(val) {
  if (!val || typeof val !== "object") return {};
  const out = {};
  for (const [k, v] of Object.entries(val)) {
    const n = Number(v);
    if (Number.isFinite(n)) out[k] = n;
  }
  return out;
}
function profitCategoryFromDb(row) {
  return {
    id: row.id,
    name: row.name || "",
    type: row.type === "ad" ? "ad" : "revenue",
    legacyColumn: row.legacy_column || null,
    sortOrder: Number(row.sort_order) || 0,
    isVisible: row.is_visible === false ? false : true,
    isCustom: !!row.is_custom
  };
}

// src/lib/connectorCore/finance.ts
var isoDay = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
var monthsAgoFirst = (now, n) => new Date(now.getFullYear(), now.getMonth() - n, 1);
async function fetchCategories(client, userId) {
  const { data, error } = await client.from("profit_categories").select("*").eq("user_id", userId);
  if (error) throw error;
  return (data ?? []).map(profitCategoryFromDb);
}
async function listDailyRecords(client, userId, opts) {
  let fromDate = opts?.fromDate;
  if (!fromDate) {
    const cutoff = /* @__PURE__ */ new Date();
    cutoff.setDate(cutoff.getDate() - 90);
    fromDate = isoDay(cutoff);
  }
  const [recordsRes, categories] = await Promise.all([
    client.from("daily_records").select("*").eq("user_id", userId).gte("date", fromDate).order("date"),
    fetchCategories(client, userId)
  ]);
  if (recordsRes.error) throw recordsRes.error;
  return (recordsRes.data ?? []).map((row) => {
    const record = dailyRecordFromDb(row);
    const m = calculateMetrics(record, categories);
    return {
      ...record,
      totalRevenue: m.totalRevenue,
      totalAdSpend: m.totalAdSpend,
      net: m.netRevenue
    };
  });
}
async function listProfitCategories(client, userId) {
  return fetchCategories(client, userId);
}
async function getPnlSummary(client, userId, opts) {
  const now = opts?.now ?? /* @__PURE__ */ new Date();
  const months = opts?.months && opts.months > 0 ? opts.months : 6;
  const fromDate = isoDay(monthsAgoFirst(now, months - 1));
  const [recordsRes, categories] = await Promise.all([
    client.from("daily_records").select("*").eq("user_id", userId).gte("date", fromDate).order("date"),
    fetchCategories(client, userId)
  ]);
  if (recordsRes.error) throw recordsRes.error;
  const byMonth = /* @__PURE__ */ new Map();
  const totals = { revenue: 0, adSpend: 0, net: 0 };
  for (const row of recordsRes.data ?? []) {
    const record = dailyRecordFromDb(row);
    const monthKey = record.date.substring(0, 7);
    const m = calculateMetrics(record, categories);
    let entry = byMonth.get(monthKey);
    if (!entry) {
      entry = { month: monthKey, revenue: 0, adSpend: 0, net: 0 };
      byMonth.set(monthKey, entry);
    }
    entry.revenue += m.totalRevenue;
    entry.adSpend += m.totalAdSpend;
    entry.net += m.netRevenue;
    totals.revenue += m.totalRevenue;
    totals.adSpend += m.totalAdSpend;
    totals.net += m.netRevenue;
  }
  const monthsOut = Array.from(byMonth.values()).sort(
    (a, b) => a.month.localeCompare(b.month)
  );
  return { months: monthsOut, totals };
}

// src/lib/connectorCore/transactions.ts
async function listTransactions(client, userId, opts) {
  const limit = opts?.limit && opts.limit > 0 ? opts.limit : 200;
  let query = client.from("transactions").select("*").eq("user_id", userId).order("date", { ascending: false });
  if (opts?.fromDate) query = query.gte("date", opts.fromDate);
  if (opts?.toDate) query = query.lte("date", opts.toDate);
  const { data, error } = await query.limit(limit);
  if (error) throw error;
  return data ?? [];
}
async function getMonthlyTransactionSummary(client, userId, opts) {
  const now = opts?.now ?? /* @__PURE__ */ new Date();
  const months = opts?.months && opts.months > 0 ? opts.months : 6;
  const first = new Date(now.getFullYear(), now.getMonth() - (months - 1), 1);
  const fromMonth = `${first.getFullYear()}-${String(first.getMonth() + 1).padStart(2, "0")}`;
  const { data, error } = await client.from("transactions").select("date, amount, type").eq("user_id", userId).gte("date", fromMonth).order("date", { ascending: false });
  if (error) throw error;
  const byMonth = /* @__PURE__ */ new Map();
  for (const tx of data ?? []) {
    const month = String(tx.date).substring(0, 7);
    let entry = byMonth.get(month);
    if (!entry) {
      entry = { month, income: 0, expenses: 0, net: 0 };
      byMonth.set(month, entry);
    }
    const amt = Math.abs(Number(tx.amount) || 0);
    if (tx.type === "income") entry.income += amt;
    else entry.expenses += amt;
    entry.net = entry.income - entry.expenses;
  }
  return Array.from(byMonth.values()).sort((a, b) => b.month.localeCompare(a.month));
}
async function listSubscriptions(client, userId) {
  const { data, error } = await client.from("manual_subscriptions").select("*").eq("user_id", userId).order("vendor_name");
  if (error) throw error;
  return data ?? [];
}
async function listCashFlowNotes(client, userId) {
  const { data, error } = await client.from("cash_flow_notes").select("*").eq("user_id", userId).order("month", { ascending: false });
  if (error) throw error;
  return data ?? [];
}
async function addTransaction(client, userId, args) {
  if (!args.date) throw new Error("addTransaction: date is required (YYYY-MM-DD)");
  if (args.type !== "income" && args.type !== "expense") {
    throw new Error(`addTransaction: invalid type '${args.type}' (expected 'income' | 'expense')`);
  }
  const amount = Number(args.amount);
  if (!Number.isFinite(amount)) throw new Error("addTransaction: amount must be a finite number");
  const description = args.description ?? "";
  const row = {
    user_id: userId,
    date: args.date,
    description,
    original_description: args.original_description ?? description,
    amount: Math.abs(amount),
    category: args.category ?? "Uncategorized",
    source: args.source ?? "",
    type: args.type
  };
  const { data, error } = await client.from("transactions").insert(row).select().single();
  if (error) throw error;
  return data;
}
async function saveCashFlowNote(client, userId, args) {
  if (!args.month) throw new Error("saveCashFlowNote: month is required (YYYY-MM)");
  const { data, error } = await client.from("cash_flow_notes").upsert(
    {
      user_id: userId,
      month: args.month,
      note: args.note ?? "",
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    },
    { onConflict: "user_id,month" }
  ).select().single();
  if (error) throw error;
  return data;
}
var MAX_IMPORT_ROWS = 1e3;
function transactionDedupKey(t) {
  const desc = String(t.original_description ?? t.description ?? "").trim().toLowerCase();
  const amt = Math.abs(Number(t.amount)).toFixed(2);
  return `${String(t.date).trim()}|${amt}|${t.type}|${desc}`;
}
async function importTransactions(client, userId, rows) {
  if (!Array.isArray(rows)) throw new Error("importTransactions: rows must be an array");
  if (rows.length === 0) return { inserted: 0, skipped: 0, insertedRows: [] };
  if (rows.length > MAX_IMPORT_ROWS) {
    throw new Error(
      `importTransactions: batch of ${rows.length} exceeds the ${MAX_IMPORT_ROWS}-row limit; split the CSV into smaller batches`
    );
  }
  const normalized = rows.map((r, i) => {
    if (!r || typeof r !== "object") throw new Error(`importTransactions: row ${i} is not an object`);
    if (!r.date || typeof r.date !== "string") {
      throw new Error(`importTransactions: row ${i} is missing a date (YYYY-MM-DD)`);
    }
    if (r.type !== "income" && r.type !== "expense") {
      throw new Error(`importTransactions: row ${i} has invalid type '${r.type}' (expected 'income' | 'expense')`);
    }
    const amount = Number(r.amount);
    if (!Number.isFinite(amount)) {
      throw new Error(`importTransactions: row ${i} has a non-finite amount`);
    }
    if (amount < 0) {
      throw new Error(`importTransactions: row ${i} has a negative amount; amounts must be >= 0 (store positive, type decides income/expense)`);
    }
    const description = r.description ?? "";
    return {
      user_id: userId,
      date: r.date,
      description,
      original_description: r.original_description ?? description,
      amount: Math.abs(amount),
      category: r.category ?? "Uncategorized",
      source: r.source ?? "",
      type: r.type
    };
  });
  let minDate = normalized[0].date;
  let maxDate = normalized[0].date;
  for (const n of normalized) {
    if (n.date < minDate) minDate = n.date;
    if (n.date > maxDate) maxDate = n.date;
  }
  const { data: existing, error: fetchError } = await client.from("transactions").select("date, amount, type, description, original_description").eq("user_id", userId).gte("date", minDate).lte("date", maxDate);
  if (fetchError) throw fetchError;
  const seen = /* @__PURE__ */ new Set();
  for (const e of existing ?? []) seen.add(transactionDedupKey(e));
  const toInsert = [];
  let skipped = 0;
  for (const n of normalized) {
    const key = transactionDedupKey(n);
    if (seen.has(key)) {
      skipped++;
      continue;
    }
    seen.add(key);
    toInsert.push(n);
  }
  if (toInsert.length === 0) {
    return { inserted: 0, skipped, insertedRows: [] };
  }
  const { data, error } = await client.from("transactions").insert(toInsert).select();
  if (error) throw error;
  const insertedRows = data ?? [];
  return { inserted: insertedRows.length, skipped, insertedRows };
}

// src/lib/connectorCore/inventory.ts
var PRODUCT_COLUMNS = "id, name, sku, category, base_price, production_cost, shipping_cost, book_inventory, bundles_inventory, six_month_book_sales, six_month_bundle_sales, lead_time, csv_avg_daily, csv_reorder_threshold, do_not_reorder";
async function listProducts(client, userId) {
  const { data, error } = await client.from("products").select(PRODUCT_COLUMNS).eq("user_id", userId).order("name", { ascending: true });
  if (error) throw error;
  return data ?? [];
}
var PO_COLUMNS = "id, product_id, product_name, quantity, actual_quantity, status, vendor, po_number, order_date, expected_arrival, actual_arrival, created_at";
async function listPurchaseOrders(client, userId, opts = {}) {
  let q = client.from("purchase_orders").select(PO_COLUMNS).eq("user_id", userId);
  if (opts.status) q = q.eq("status", opts.status);
  const { data, error } = await q.order("created_at", { ascending: false });
  if (error) throw error;
  return data ?? [];
}
var isoDay2 = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
async function listOrders(client, userId, opts = {}) {
  const limit = opts.limit ?? 200;
  let fromDate = opts.fromDate;
  if (!fromDate) {
    const cutoff = /* @__PURE__ */ new Date();
    cutoff.setDate(cutoff.getDate() - 30);
    fromDate = isoDay2(cutoff);
  }
  const { data, error } = await client.from("shopify_orders").select(
    "id, order_number, order_date, customer_name, financial_status, fulfillment_status, total_price, cancelled_at, line_items"
  ).eq("user_id", userId).gte("order_date", fromDate).order("order_date", { ascending: false }).limit(limit);
  if (error) throw error;
  return (data ?? []).map((o) => {
    const items = Array.isArray(o.line_items) ? o.line_items : [];
    const itemQuantity = items.reduce((sum, it) => sum + (Number(it?.quantity) || 0), 0);
    return {
      id: o.id,
      order_number: o.order_number,
      order_date: o.order_date,
      customer_name: o.customer_name ?? "",
      financial_status: o.financial_status ?? "",
      fulfillment_status: o.fulfillment_status ?? "",
      total_price: Number(o.total_price) || 0,
      cancelled_at: o.cancelled_at,
      lineItemCount: items.length,
      itemQuantity
    };
  });
}

// src/lib/connectorCore/planner.ts
var isoDay3 = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
var TASK_COLUMNS = "id, note_id, kind, title, notes, done, done_at, due_date, someday, flagged, feel_good, in_orbit, estimate_minutes, recurrence, sort_order, created_at, updated_at";
var toTaskSummary = (r) => ({
  id: r.id,
  list_id: r.note_id,
  kind: r.kind,
  title: r.title,
  notes: r.notes,
  done: r.done,
  done_at: r.done_at,
  due_date: r.due_date,
  someday: r.someday,
  flagged: r.flagged,
  feel_good: r.feel_good,
  in_orbit: r.in_orbit,
  estimate_minutes: r.estimate_minutes,
  recurrence: r.recurrence,
  sort_order: r.sort_order,
  created_at: r.created_at,
  updated_at: r.updated_at
});
async function listTasks(client, userId, opts = {}) {
  const done = opts.done ?? false;
  const limit = opts.limit ?? 200;
  let q = client.from("planner_tasks").select(TASK_COLUMNS).eq("user_id", userId).eq("done", done);
  if (opts.listId !== void 0) q = q.eq("note_id", opts.listId);
  if (opts.dueBefore) q = q.lt("due_date", opts.dueBefore);
  if (opts.someday !== void 0) q = q.eq("someday", opts.someday);
  const { data, error } = await q.order("due_date", { ascending: true, nullsFirst: false }).order("sort_order", { ascending: true }).limit(limit);
  if (error) throw error;
  return (data ?? []).map(toTaskSummary);
}
async function listTaskLists(client, userId) {
  const { data, error } = await client.from("planner_notes").select("id, title, archived, pinned, sort_order").eq("user_id", userId).order("pinned", { ascending: false }).order("sort_order", { ascending: true });
  if (error) throw error;
  return data ?? [];
}
async function createList(client, userId, args) {
  const row = {
    user_id: userId,
    title: args.title,
    archived: false
  };
  if (args.pinned != null) row.pinned = args.pinned;
  const { data, error } = await client.from("planner_notes").insert(row).select("id, title, archived, pinned, sort_order").single();
  if (error) throw error;
  return data;
}
async function getTaskCounts(client, userId, now = /* @__PURE__ */ new Date()) {
  const todayIso = isoDay3(now);
  const { data, error } = await client.from("planner_tasks").select("done, due_date, someday").eq("user_id", userId).eq("kind", "task");
  if (error) throw error;
  const rows = data ?? [];
  let open = 0;
  let done = 0;
  let overdue = 0;
  let someday = 0;
  for (const r of rows) {
    if (r.done) {
      done += 1;
      continue;
    }
    open += 1;
    if (r.someday) someday += 1;
    if (!r.someday && r.due_date && r.due_date < todayIso) overdue += 1;
  }
  return { open, done, overdue, someday };
}
async function createTask(client, userId, args) {
  const row = {
    user_id: userId,
    kind: "task",
    title: args.title,
    done: false,
    note_id: args.listId ?? null,
    due_date: args.dueDate ?? null,
    someday: args.someday ?? false
  };
  if (args.priority != null) row.flagged = args.priority;
  if (args.feelGood != null) row.feel_good = args.feelGood;
  if (args.estimateMinutes != null) row.estimate_minutes = args.estimateMinutes;
  const { data, error } = await client.from("planner_tasks").insert(row).select(TASK_COLUMNS).single();
  if (error) throw error;
  return toTaskSummary(data);
}
async function completeTask(client, userId, args) {
  const { data, error } = await client.from("planner_tasks").update({
    done: true,
    done_at: (/* @__PURE__ */ new Date()).toISOString(),
    updated_at: (/* @__PURE__ */ new Date()).toISOString()
  }).eq("user_id", userId).eq("id", args.taskId).select(TASK_COLUMNS).single();
  if (error) throw error;
  return toTaskSummary(data);
}
var ADD_TASKS_MAX = 200;
async function addTasks(client, userId, tasks) {
  if (tasks.length === 0) return [];
  if (tasks.length > ADD_TASKS_MAX) {
    throw new Error(
      `addTasks: too many tasks (${tasks.length}); cap is ${ADD_TASKS_MAX} per call. Split the import into smaller batches.`
    );
  }
  const rows = tasks.map((t) => ({
    user_id: userId,
    kind: "task",
    title: t.title,
    done: false,
    note_id: t.listId ?? null,
    due_date: t.dueDate ?? null
  }));
  const { data, error } = await client.from("planner_tasks").insert(rows).select(TASK_COLUMNS);
  if (error) throw error;
  return (data ?? []).map(toTaskSummary);
}

// src/lib/connectorCore/cashflow.ts
function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}
function orderLines(lines) {
  return [...lines].sort((a, b) => {
    const da = a.line_date ?? "";
    const db = b.line_date ?? "";
    if (da && db) {
      if (da !== db) return da < db ? -1 : 1;
    } else if (da || db) {
      return da ? -1 : 1;
    }
    return String(a.created_at).localeCompare(String(b.created_at));
  });
}
function buildWeek(week, lines) {
  const income = orderLines(lines.filter((l) => l.kind === "income"));
  const bills = orderLines(lines.filter((l) => l.kind === "bill"));
  const incomeSubtotal = income.reduce((s, l) => s + num(l.amount), 0);
  const billsSubtotal = bills.reduce((s, l) => s + num(l.amount), 0);
  const hasOpening = week.opening_balance !== null && week.opening_balance !== void 0;
  const opening = num(week.opening_balance);
  return {
    week,
    income,
    bills,
    incomeSubtotal,
    billsSubtotal,
    worstCaseEnding: hasOpening ? opening - billsSubtotal : null,
    projectedEnding: hasOpening ? opening + incomeSubtotal - billsSubtotal : null
  };
}
async function getCashFlow(client, userId, opts) {
  let weekQuery = client.from("cash_flow_weeks").select("*").eq("user_id", userId).order("week_start", { ascending: true });
  if (opts?.weekStart) {
    weekQuery = weekQuery.eq("week_start", opts.weekStart);
  } else if (opts?.month) {
    const { start, end } = monthBounds(opts.month);
    weekQuery = weekQuery.gte("week_start", start).lt("week_start", end);
  }
  const { data: weeks, error: weeksErr } = await weekQuery;
  if (weeksErr) throw weeksErr;
  const weekRows = weeks ?? [];
  if (weekRows.length === 0) return [];
  const weekIds = weekRows.map((w) => w.id);
  const { data: lines, error: linesErr } = await client.from("cash_flow_lines").select("*").eq("user_id", userId).in("week_id", weekIds);
  if (linesErr) throw linesErr;
  const byWeek = /* @__PURE__ */ new Map();
  for (const line of lines ?? []) {
    const arr = byWeek.get(line.week_id);
    if (arr) arr.push(line);
    else byWeek.set(line.week_id, [line]);
  }
  return weekRows.map((w) => buildWeek(w, byWeek.get(w.id) ?? []));
}
function monthBounds(month) {
  const m = /^(\d{4})-(\d{2})$/.exec(month);
  if (!m) throw new Error(`getCashFlow: invalid month '${month}' (expected YYYY-MM)`);
  const year = Number(m[1]);
  const mon = Number(m[2]);
  const start = `${m[1]}-${m[2]}-01`;
  const nextYear = mon === 12 ? year + 1 : year;
  const nextMon = mon === 12 ? 1 : mon + 1;
  const end = `${String(nextYear).padStart(4, "0")}-${String(nextMon).padStart(2, "0")}-01`;
  return { start, end };
}
async function upsertCashFlowWeek(client, userId, args) {
  if (!args.weekStart) throw new Error("upsertCashFlowWeek: weekStart is required (YYYY-MM-DD)");
  if (!args.weekEnd) throw new Error("upsertCashFlowWeek: weekEnd is required (YYYY-MM-DD)");
  const row = {
    user_id: userId,
    week_start: args.weekStart,
    week_end: args.weekEnd,
    updated_at: (/* @__PURE__ */ new Date()).toISOString()
  };
  if (args.openingBalance !== void 0) row.opening_balance = args.openingBalance;
  if (args.actualEndingBalance !== void 0) row.actual_ending_balance = args.actualEndingBalance;
  if (args.note !== void 0) row.note = args.note;
  const { data, error } = await client.from("cash_flow_weeks").upsert(row, { onConflict: "user_id,week_start" }).select().single();
  if (error) throw error;
  return data;
}
async function addCashFlowLine(client, userId, args) {
  if (!args.weekStart) throw new Error("addCashFlowLine: weekStart is required (YYYY-MM-DD)");
  if (args.kind !== "income" && args.kind !== "bill") {
    throw new Error(`addCashFlowLine: invalid kind '${args.kind}' (expected 'income' | 'bill')`);
  }
  const amount = Number(args.amount);
  if (!Number.isFinite(amount)) throw new Error("addCashFlowLine: amount must be a finite number");
  const { data: week, error: weekErr } = await client.from("cash_flow_weeks").select("id").eq("user_id", userId).eq("week_start", args.weekStart).maybeSingle();
  if (weekErr) throw weekErr;
  if (!week) {
    throw new Error(
      `addCashFlowLine: no cash-flow week exists for week_start ${args.weekStart}. Create it first with upsertCashFlowWeek({ weekStart, weekEnd }).`
    );
  }
  const row = {
    user_id: userId,
    week_id: week.id,
    kind: args.kind,
    line_date: args.date ?? null,
    source: args.source ?? "",
    amount,
    settled: args.settled ?? false,
    notes: args.notes ?? null
  };
  const { data, error } = await client.from("cash_flow_lines").insert(row).select().single();
  if (error) throw error;
  return data;
}
async function updateCashFlowLine(client, userId, args) {
  if (!args.lineId) throw new Error("updateCashFlowLine: lineId is required");
  const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
  if (args.source !== void 0) patch.source = args.source;
  if (args.amount !== void 0) {
    const amount = Number(args.amount);
    if (!Number.isFinite(amount)) throw new Error("updateCashFlowLine: amount must be a finite number");
    patch.amount = amount;
  }
  if (args.settled !== void 0) patch.settled = args.settled;
  if (args.date !== void 0) patch.line_date = args.date;
  if (args.notes !== void 0) patch.notes = args.notes;
  const { data, error } = await client.from("cash_flow_lines").update(patch).eq("user_id", userId).eq("id", args.lineId).select().single();
  if (error) throw error;
  return data;
}
async function deleteCashFlowLine(client, userId, args) {
  if (!args.lineId) throw new Error("deleteCashFlowLine: lineId is required");
  const { error } = await client.from("cash_flow_lines").delete().eq("user_id", userId).eq("id", args.lineId);
  if (error) throw error;
  return { deleted: true };
}
export {
  ADD_TASKS_MAX,
  addCashFlowLine,
  addTasks,
  addTransaction,
  appendManuscriptChapter,
  completeTask,
  createList,
  createManuscript,
  createTask,
  deleteCashFlowLine,
  getArcStats,
  getBook,
  getCashFlow,
  getChapter,
  getManuscript,
  getManuscriptPlainText,
  getMonthlyTransactionSummary,
  getPnlSummary,
  getTaskCounts,
  importTransactions,
  listArcReaders,
  listBooks,
  listCashFlowNotes,
  listDailyRecords,
  listManuscripts,
  listOrders,
  listPenNames,
  listProducts,
  listProfitCategories,
  listPurchaseOrders,
  listSubscriptions,
  listTaskLists,
  listTasks,
  listTransactions,
  saveCashFlowNote,
  setOpportunityDecision,
  updateCashFlowLine,
  upsertCashFlowWeek
};
