// GENERATED by scripts/bundle-mcp-core.mjs — do not edit by hand.
// Source of truth: src/lib/dashboardCore.ts. Run `npm run bundle:mcp` to refresh.

// src/modules/inventory/utils.ts
var FEE_RATES = {
  TRANSACTION_FEE_PERCENT: 0.029,
  // 2.9% for standard payment processing
  TRANSACTION_FEE_FIXED: 0.3,
  // $0.30 fixed per transaction
  TIKTOK_FEE_PERCENT: 0.08,
  // 8% TikTok Shop fee
  TIKTOK_FEE_FIXED: 0.3
  // $0.30 fixed TikTok fee
};
function calculateProductMetrics(product, allProducts, avgDailyFromOrders) {
  const transactionFees = product.base_price > 0 ? product.base_price * FEE_RATES.TRANSACTION_FEE_PERCENT + FEE_RATES.TRANSACTION_FEE_FIXED : 0;
  const printerCost = product.production_cost + product.shipping_cost + product.shipping_supplies_cost;
  const paTotal = product.pa_costs + product.qa_cost;
  const totalCostPerUnit = printerCost + paTotal + transactionFees;
  const revenuePerUnit = product.base_price + product.handling_fee_add_on;
  const netMargin = revenuePerUnit - totalCostPerUnit;
  const netMarginPercent = product.base_price > 0 ? netMargin / product.base_price * 100 : 0;
  const defectFactor = Math.max(0, product.defect_rate || 0) / 100;
  const reprintQaCost = product.qa_cost * defectFactor;
  const trueCostPerGoodBook = totalCostPerUnit + reprintQaCost;
  const trueNetMargin = revenuePerUnit - trueCostPerGoodBook;
  const trueNetMarginPercent = product.base_price > 0 ? trueNetMargin / product.base_price * 100 : 0;
  const ttFees = product.tt_shop_price > 0 ? product.tt_shop_price * FEE_RATES.TIKTOK_FEE_PERCENT + FEE_RATES.TIKTOK_FEE_FIXED : 0;
  const ttTotalCostPerUnit = product.production_cost + product.free_shipping + product.shipping_supplies_cost + paTotal + ttFees;
  const ttNetMargin = product.tt_shop_price - ttTotalCostPerUnit;
  const ttNetMarginPercent = product.tt_shop_price > 0 ? ttNetMargin / product.tt_shop_price * 100 : 0;
  const bookInventory = product.book_inventory;
  let bundlesInventory = product.bundles_inventory;
  if ((product.category === "Bundle" || product.category === "Book Box") && product.books_in_bundle && allProducts) {
    bundlesInventory = calculateBundleInventory(product, allProducts);
  }
  const csvAvgDaily = Number(product.csv_avg_daily) || 0;
  const sixMoBook = Number(product.six_month_book_sales) || 0;
  const sixMoBundle = Number(product.six_month_bundle_sales) || 0;
  const leadTime = Number(product.lead_time) || 0;
  const shopifyDaily = Number(avgDailyFromOrders) || 0;
  const avgDailySales = csvAvgDaily > 0 ? csvAvgDaily : shopifyDaily > 0 ? shopifyDaily : (sixMoBook + sixMoBundle) / 180;
  const avgDailySource = csvAvgDaily > 0 ? "override" : shopifyDaily > 0 ? "shopify" : sixMoBook + sixMoBundle > 0 ? "six_month" : "none";
  const reorderThreshold = Math.ceil(avgDailySales * leadTime);
  let daysRemaining;
  if (product.category === "Bundle" || product.category === "Book Box") {
    daysRemaining = avgDailySales > 0 ? Math.round(bundlesInventory / avgDailySales) : Infinity;
  } else {
    daysRemaining = avgDailySales > 0 ? Math.round(bookInventory / avgDailySales) : Infinity;
  }
  let status;
  if (product.category === "Bundle" || product.category === "Book Box") {
    status = "BUNDLE";
  } else if (product.do_not_reorder) {
    status = "TRACKING ONLY";
  } else if (bookInventory <= 0) {
    status = "OUT OF STOCK";
  } else if (bookInventory <= reorderThreshold && reorderThreshold > 0) {
    status = "REORDER NOW";
  } else if (daysRemaining !== Infinity && daysRemaining <= leadTime) {
    status = "REORDER NOW";
  } else {
    status = "Good";
  }
  let reorderQty = 0;
  if (status === "REORDER NOW" || status === "OUT OF STOCK") {
    reorderQty = Math.round(Math.max(
      reorderThreshold - bookInventory + avgDailySales * leadTime,
      0
    ));
  }
  const reorderCost = reorderQty * (product.production_cost + product.shipping_cost);
  let action;
  if (product.category === "Bundle" || product.category === "Book Box") {
    action = "BUNDLE";
  } else if (status === "OUT OF STOCK") {
    action = "REORDER NOW";
  } else if (status === "REORDER NOW") {
    action = "ORDER THIS WEEK";
  } else {
    action = "NO ACTION NEEDED";
  }
  return {
    transactionFees,
    printerCost,
    paTotal,
    totalCostPerUnit,
    revenuePerUnit,
    netMargin,
    netMarginPercent,
    reprintQaCost,
    trueCostPerGoodBook,
    trueNetMargin,
    trueNetMarginPercent,
    ttFees,
    ttTotalCostPerUnit,
    ttNetMargin,
    ttNetMarginPercent,
    bookInventory,
    bundlesInventory,
    avgDailySales,
    avgDailySource,
    reorderThreshold,
    daysRemaining,
    reorderQty,
    reorderCost,
    status,
    action
  };
}
function calculateBundleInventory(product, allProducts) {
  if (!product.books_in_bundle) return product.bundles_inventory;
  const componentNames = product.books_in_bundle.split(",").map((name) => name.trim()).filter(Boolean);
  if (componentNames.length === 0) return product.bundles_inventory;
  const componentInventories = [];
  for (const name of componentNames) {
    const nameLower = name.toLowerCase();
    const match = allProducts.find((p) => p.name.toLowerCase() === nameLower) || allProducts.find((p) => p.name.toLowerCase().startsWith(nameLower) || nameLower.startsWith(p.name.toLowerCase()));
    if (match && match.category !== "Bundle" && match.category !== "Book Box") {
      const inv = match.book_stock - (match.books_purchased + match.purchased_via_bundles);
      componentInventories.push(inv);
    }
  }
  if (componentInventories.length === 0) return product.bundles_inventory;
  return Math.min(...componentInventories);
}
function aggregateSalesRates(rows, windowDays) {
  const totals = /* @__PURE__ */ new Map();
  for (const row of rows) {
    if (row.cancelled_at) continue;
    const items = row.line_items || [];
    const refunds = row.refunds || [];
    const refundedByLineItem = /* @__PURE__ */ new Map();
    for (const r of refunds) {
      for (const rli of r.refund_line_items || []) {
        if (rli.line_item_id == null) continue;
        refundedByLineItem.set(rli.line_item_id, (refundedByLineItem.get(rli.line_item_id) || 0) + (Number(rli.quantity) || 0));
      }
    }
    for (const it of items) {
      const rawSku = (it?.sku || "").trim();
      if (!rawSku) continue;
      const key = rawSku.toUpperCase();
      const refunded = it.id != null ? refundedByLineItem.get(it.id) || 0 : 0;
      const netQty = (Number(it?.quantity) || 0) - refunded;
      if (netQty <= 0) continue;
      totals.set(key, (totals.get(key) || 0) + netQty);
    }
  }
  const map = /* @__PURE__ */ new Map();
  for (const [sku, total] of totals) {
    map.set(sku, { totalSold: total, avgDaily: total / windowDays, windowDays });
  }
  return map;
}

// src/modules/profit-track/utils/calculations.ts
var calculateMetrics = (record, categories) => {
  const legacyAds = (record.pnrAds || 0) + (record.contempAds || 0) + (record.trafficAds || 0) + (record.miscAds || 0);
  const legacyRev = (record.shopifyRev || 0) + (record.amazonRev || 0) + (record.d2dRev || 0) + (record.googleRev || 0) + (record.koboRev || 0) + (record.koboPlusRev || 0);
  let customAds = 0;
  let customRev = 0;
  if (categories && record.customAmounts) {
    for (const cat of categories) {
      if (cat.legacyColumn) continue;
      const amt = record.customAmounts[cat.id] || 0;
      if (cat.type === "ad") customAds += amt;
      else customRev += amt;
    }
  }
  const totalAdSpend = legacyAds + customAds;
  const totalRevenue = legacyRev + customRev;
  const netRevenue = totalRevenue - totalAdSpend;
  const roas = totalAdSpend > 0 ? totalRevenue / totalAdSpend : 0;
  const adsToIncomePercent = totalRevenue > 0 ? totalAdSpend / totalRevenue : 0;
  return { totalAdSpend, totalRevenue, netRevenue, roas, adsToIncomePercent };
};

// src/modules/profit-track/utils/mappers.ts
function dailyRecordFromDb(row) {
  return {
    id: row.id,
    date: row.date,
    pnrAds: Number(row.pnr_ads) || 0,
    contempAds: Number(row.contemp_ads) || 0,
    trafficAds: Number(row.traffic_ads) || 0,
    miscAds: Number(row.misc_ads) || 0,
    shopifyRev: Number(row.shopify_rev) || 0,
    amazonRev: Number(row.amazon_rev) || 0,
    d2dRev: Number(row.d2d_rev) || 0,
    googleRev: Number(row.google_rev) || 0,
    koboRev: Number(row.kobo_rev) || 0,
    koboPlusRev: Number(row.kobo_plus_rev) || 0,
    customAmounts: normalizeCustomAmounts(row.custom_amounts)
  };
}
function normalizeCustomAmounts(val) {
  if (!val || typeof val !== "object") return {};
  const out = {};
  for (const [k, v] of Object.entries(val)) {
    const n = Number(v);
    if (Number.isFinite(n)) out[k] = n;
  }
  return out;
}
function profitCategoryFromDb(row) {
  return {
    id: row.id,
    name: row.name || "",
    type: row.type === "ad" ? "ad" : "revenue",
    legacyColumn: row.legacy_column || null,
    sortOrder: Number(row.sort_order) || 0,
    isVisible: row.is_visible === false ? false : true,
    isCustom: !!row.is_custom
  };
}

// src/lib/dashboardCore.ts
var isoDay = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
async function getInventoryAlertsCore(client) {
  const cutoff = /* @__PURE__ */ new Date();
  cutoff.setDate(cutoff.getDate() - 180);
  const [productsRes, ordersRes, pendingRes] = await Promise.all([
    client.from("products").select("*"),
    client.from("shopify_orders").select("order_date, line_items, refunds, cancelled_at").gte("order_date", cutoff.toISOString()),
    client.from("purchase_orders").select("product_id, quantity").eq("status", "pending")
  ]);
  if (productsRes.error) throw productsRes.error;
  const products = productsRes.data ?? [];
  const salesRates = aggregateSalesRates(ordersRes.error ? [] : ordersRes.data ?? [], 180);
  const pendingByProduct = /* @__PURE__ */ new Map();
  if (!pendingRes.error) {
    for (const po of pendingRes.data ?? []) {
      pendingByProduct.set(po.product_id, (pendingByProduct.get(po.product_id) ?? 0) + (Number(po.quantity) || 0));
    }
  }
  const alerts = [];
  for (const p of products) {
    if (p.do_not_reorder) continue;
    const sku = (p.sku || "").trim().toUpperCase();
    const shopifyDaily = sku ? salesRates.get(sku)?.avgDaily : void 0;
    const m = calculateProductMetrics(p, products, shopifyDaily);
    if (m.status !== "REORDER NOW" && m.status !== "OUT OF STOCK") continue;
    const pending = pendingByProduct.get(p.id) ?? 0;
    if (m.reorderQty > 0 && pending >= m.reorderQty) continue;
    alerts.push({
      productId: p.id,
      name: p.name,
      sku: p.sku,
      bookInventory: m.bookInventory,
      daysRemaining: m.daysRemaining,
      reorderQty: Math.max(0, m.reorderQty - pending),
      reorderCost: m.reorderCost,
      status: m.status
    });
  }
  return alerts.sort((a, b) => a.daysRemaining - b.daysRemaining);
}
async function getMonthPnlCore(client, now = /* @__PURE__ */ new Date()) {
  const first = new Date(now.getFullYear(), now.getMonth(), 1);
  const prevFirst = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const [recordsRes, categoriesRes] = await Promise.all([
    client.from("daily_records").select("*").gte("date", isoDay(prevFirst)).order("date"),
    client.from("profit_categories").select("*")
  ]);
  if (recordsRes.error) throw recordsRes.error;
  if (categoriesRes.error) throw categoriesRes.error;
  const categories = (categoriesRes.data ?? []).map(profitCategoryFromDb);
  const records = (recordsRes.data ?? []).map(dailyRecordFromDb);
  const firstIso = isoDay(first);
  let monthRevenue = 0;
  let monthAdSpend = 0;
  let prevMonthNet = 0;
  let lastEntryDate = null;
  for (const r of records) {
    const m = calculateMetrics(r, categories);
    if (r.date >= firstIso) {
      monthRevenue += m.totalRevenue;
      monthAdSpend += m.totalAdSpend;
      if (!lastEntryDate || r.date > lastEntryDate) lastEntryDate = r.date;
    } else {
      prevMonthNet += m.totalRevenue - m.totalAdSpend;
    }
  }
  return { monthRevenue, monthAdSpend, monthNet: monthRevenue - monthAdSpend, prevMonthNet, lastEntryDate };
}
async function getUpcomingDatesCore(client, userId, days = 14, now = /* @__PURE__ */ new Date()) {
  const todayIso = isoDay(now);
  const end = new Date(now);
  end.setDate(end.getDate() + days);
  const endIso = isoDay(end);
  const [booksRes, tasksRes] = await Promise.all([
    client.from("books").select("id, title, publish_date, pre_order_date, manuscript_due_date").eq("user_id", userId).or(
      `and(publish_date.gte.${todayIso},publish_date.lte.${endIso}),and(pre_order_date.gte.${todayIso},pre_order_date.lte.${endIso}),and(manuscript_due_date.gte.${todayIso},manuscript_due_date.lte.${endIso})`
    ),
    client.from("planner_tasks").select("id, title, due_date").eq("user_id", userId).eq("done", false).eq("kind", "task").eq("someday", false).gte("due_date", todayIso).lte("due_date", endIso).order("due_date").limit(30)
  ]);
  if (booksRes.error) throw booksRes.error;
  if (tasksRes.error) throw tasksRes.error;
  const items = [];
  const inRange = (d) => !!d && d >= todayIso && d <= endIso;
  for (const b of booksRes.data ?? []) {
    if (inRange(b.publish_date)) {
      items.push({ date: b.publish_date, label: `\u201C${b.title}\u201D releases`, kind: "release", href: "/catalog" });
    }
    if (inRange(b.pre_order_date)) {
      items.push({ date: b.pre_order_date, label: `\u201C${b.title}\u201D pre-order goes live`, kind: "pre_order", href: "/catalog" });
    }
    if (inRange(b.manuscript_due_date)) {
      items.push({ date: b.manuscript_due_date, label: `\u201C${b.title}\u201D manuscript due`, kind: "manuscript_due", href: "/writing" });
    }
  }
  for (const t of tasksRes.data ?? []) {
    items.push({ date: t.due_date, label: t.title, kind: "task", href: "/planner" });
  }
  return items.sort((a, b) => a.date.localeCompare(b.date));
}
async function getTodayTasksCore(client, userId, now = /* @__PURE__ */ new Date()) {
  const todayIso = isoDay(now);
  const { data, error } = await client.from("planner_tasks").select("title, due_date").eq("user_id", userId).eq("done", false).eq("kind", "task").eq("someday", false).lte("due_date", todayIso).order("due_date").limit(50);
  if (error) throw error;
  const rows = data ?? [];
  return {
    count: rows.length,
    titles: rows.map((r) => r.title),
    overdueCount: rows.filter((r) => r.due_date < todayIso).length
  };
}
async function getBusinessSnapshot(client, userId, now = /* @__PURE__ */ new Date()) {
  const [tasks, inventoryAlerts, monthPnl, upcoming] = await Promise.all([
    getTodayTasksCore(client, userId, now),
    getInventoryAlertsCore(client),
    getMonthPnlCore(client, now),
    getUpcomingDatesCore(client, userId, 7, now)
  ]);
  return { today: isoDay(now), tasks, inventoryAlerts, monthPnl, upcoming };
}
export {
  getBusinessSnapshot,
  getInventoryAlertsCore,
  getMonthPnlCore,
  getTodayTasksCore,
  getUpcomingDatesCore
};
